### ISSUE TITLE
Prerequisite missing

### ISSUE THREAD

**Issue by PatrickSteiner** [jbossdemocentral/jdg-labs#6]
The list of prerequisites seems to be missing

jboss-datagrid-6.3.0-eap-modules-hotrod-java-client.zip

**Comment by qkhan001** [comment]
## On migrating lab 5 and 6  to JDG 6.6, I am getting the following errors 

Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409 Ambiguous dependencies for type [RemoteCache<Long, Task>] with qualifiers [@Default] at injection point [[field] @Inject org.jboss.infinispan.demo.TaskService.cache]. Possible dependencies [[Custom Bean with bean class interface org.infinispan.client.hotrod.RemoteCache and qualifiers [@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()], Producer Method [RemoteCache<Long, Task>] with qualifiers [@Default @Any] declared as [[method] @Produces public org.jboss.infinispan.demo.Config.getRemoteCache()]]]
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:318)
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
    at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:147)
    at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
    at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
    at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
    at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
    at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:64)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Exception 0 :
org.jboss.weld.exceptions.AmbiguousResolutionException: WELD-001318 Cannot resolve an ambiguous dependency between [Custom Bean with bean class interface org.infinispan.client.hotrod.RemoteCache and qualifiers [@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()], Producer Method [RemoteCache<Long, Task>] with qualifiers [@Default @Any] declared as [[method] @Produces public org.jboss.infinispan.demo.Config.getRemoteCache()]]
    at org.jboss.weld.manager.BeanManagerImpl.resolve(BeanManagerImpl.java:1056)
    at org.jboss.weld.bootstrap.Validator.validatePseudoScopedInjectionPoint(Validator.java:640)
    at org.jboss.weld.bootstrap.Validator.reallyValidatePseudoScopedBean(Validator.java:620)
    at org.jboss.weld.bootstrap.Validator.validatePseudoScopedInjectionPoint(Validator.java:646)
    at org.jboss.weld.bootstrap.Validator.reallyValidatePseudoScopedBean(Validator.java:620)
    at org.jboss.weld.bootstrap.Validator.validatePseudoScopedBean(Validator.java:598)
    at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:154)
    at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
    at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
    at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
    at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
    at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:64)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

## "}}
